### ISSUE TITLE
Album Artwork Size is Small

### ISSUE THREAD

**Issue by shivamrewa9981** [naqushab/saavn-downloader-extension#1]
ONLY PROBLEM IS WITH ALBUM ARTWORK!
BECAUSE THIS EXTENSION IS ALWAYS FETCHING SMALL THUMBNAILS!
So Can U fix This to A HQ Artwork Instead???

**Comment by spiDIMan** [comment]
Use [this](https://github.com/naqushab/saavn-downloader-extension/issues/1) fork I made.
ps. This is the best image Saavn has to offer.

**Comment by spiDIMan** [comment]
Use [this](https://github.com/spiDIMan/saavn-downloader-extension/tree/patch-1) fork I made.
ps. This is the best image Saavn has to offer.

**Comment by naqushab** [comment]
Looks like @spiDIMan has already fixed it. Hey @spiDIMan , care to raise a pull request for it? I will merge your changes along with it.
@shivamrewa9981 does that solve your problem?

**Comment by spiDIMan** [comment]
Added the pull request.

**Comment by naqushab** [comment]
@shivamrewa9981 This should get fixed in latest changes. Thanks to @spiDIMan
