### ISSUE TITLE
Songs not downloading properly - only 200kb in size

### ISSUE THREAD

**Issue by babz1989** [naqushab/saavn-downloader-extension#13]
When I try to download a song, it does not do it properly as the file sizes are in the 200kb range. I've tried @justiriser fix but it's not working for me 
![capture](https://user-images.githubusercontent.com/45948464/50106684-6b150d80-0228-11e9-9fb0-2c35c1b1d220.PNG)
![capture2](https://user-images.githubusercontent.com/45948464/50106705-7b2ced00-0228-11e9-8ae0-50f35f155025.PNG)

**Comment by babz1989** [comment]
maybe it's this, there's an error in the chrome extensions page
![capture3](https://user-images.githubusercontent.com/45948464/50106860-ed9dcd00-0228-11e9-89de-66e41e5d69c9.PNG)

**Comment by yashjahit-21705201** [comment]
> maybe it's this, there's an error in the chrome extensions page
> ![capture3](https://user-images.githubusercontent.com/45948464/50106860-ed9dcd00-0228-11e9-89de-66e41e5d69c9.PNG)

I don't think that is the problem, as it just means the variable len wasn't declared. It must be something on JioSaavn side

**Comment by naqushab** [comment]
Thanks for the detailed report. Will definitely look into it.

**Comment by ronxiibang** [comment]
okay i have it tested now just switch downloading quality to 128kbps on those songs which shows downloading

**Comment by yashjahit-21705201** [comment]
Also tested now and it is working again. Thank you!

**Comment by ronxiibang** [comment]
yes because those albums were old and that is reason they are not available in 320kbps on savaan

**Comment by rubbesh** [comment]
Some song have only 183kb while downloading

**Comment by naqushab** [comment]
The reason that some songs are of few KBs in size is because they are not available in selected quality (320kbps for example). Try changing the Download quality from top right dropdown and see if problem persists. There is no way to see if a song is available in a mentioned quality.

**Comment by rubbesh** [comment]
Thank you
