### ISSUE TITLE
Songs with the Tiltle (name) more than 25 letters are not downloading...

### ISSUE THREAD

**Issue by N4pst3rX** [naqushab/saavn-downloader-extension#14]
first of all thank you for making this extension it helps me a lot .. i am  facing an issue that the song name exceeds 25+ letters it won't download .. Try to fix this issue please.

**Comment by naqushab** [comment]
Can you please specify the URL of the song that made you encounter this bug?
Thanks.

**Comment by naqushab** [comment]
Closing as no response. Reopen if help is required.
