### ISSUE TITLE
Stuck on Downloading Album Artwork

### ISSUE THREAD

**Issue by Princeyadav05** [naqushab/saavn-downloader-extension#15]
Songs are not being downloaded and the script is stuck on "Downloading Album Artwork". Happening for every song.

**Comment by Princeyadav05** [comment]
Errors in the extension.
[Link](https://i.imgur.com/yeoc8kJ.jpg)

**Comment by naqushab** [comment]
Thanks @Princeyadav05 . I'll look into it. Is this happening for every song or anything in particular?

**Comment by falthu** [comment]
Can't downloading single song...please fix it

**Comment by mrajibrm** [comment]
![image](https://user-images.githubusercontent.com/44160545/54289671-944afd00-45cf-11e9-8c88-e9e45917fa07.png)


This is the error.

**Comment by yashjahit-21705201** [comment]
> ![image](https://user-images.githubusercontent.com/44160545/54289671-944afd00-45cf-11e9-8c88-e9e45917fa07.png)
> 
> This is the error.

Same error happenning here also

**Comment by Princeyadav05** [comment]
Hey @yashjahit-21705201 @mrajibrm @falthu 
Use this one: https://github.com/justiriser/JioSaavn-Downloader-Chrome-Extension/commits/master
This one is working fine.

**Comment by naqushab** [comment]
The reason that some songs are of few KBs in size is because they are not available in selected quality (320kbps for example). Try changing the Download quality from top right dropdown and see if problem persists. There is no way to see if a song is available in a mentioned quality.
