### ISSUE TITLE
Fallback to next best quality of song if a song is not available in a particular download quality

### ISSUE THREAD

**Issue by naqushab** [naqushab/saavn-downloader-extension#21]
The reason that some songs are of few KBs in size is because they are not available in selected quality (320kbps for example). There is no way to see if a song is available in a mentioned quality for now.
Playlist and Albums can have such songs will will lead to having such files in them too.

If we can fallback to next best quality that is available to download, it will solve this problem.

**Comment by dharmendra98** [comment]
I think i can give it a try.

**Comment by naqushab** [comment]
I would really appreciate the effort. Raise a PR for it whenever you can.

**Comment by HritwikSinghal** [comment]
if status code of song download url doesn't return 200, replace '_320.mp3" with '.mp3'

**Comment by naqushab** [comment]
Good catch @HritwikSinghal . I'll add that as a part of the code

**Comment by HritwikSinghal** [comment]
> Good catch @HritwikSinghal . I'll add that as a part of the code

Instead of directly falling back to 128, you can first try 160 then fall back to 128.
