### ISSUE TITLE
FLAC quality?

### ISSUE THREAD

**Issue by KannaDev** [naqushab/saavn-downloader-extension#22]
Is it possible to add FLAC (1411 kbps) quality in the download options? Lossless is so much better than 320kbps compressed mp3 files. Would love to see a FLAC option. 

Other than that great work you've done here! Really nice tool.

**Comment by naqushab** [comment]
Sorry man. Flac is no where in the json response. I hear some good things about DeezLoader and SMloadr. But not in this.
