### ISSUE TITLE
🥺Not working 😭😭

### ISSUE THREAD

**Issue by rubbesh** [naqushab/saavn-downloader-extension#25]
chrome extension not working 😿

**Comment by naqushab** [comment]
Fixed in #40 
Follow read me and you should start seeing the download options reappear

**Comment by rubbesh** [comment]
Gaana extension

**Comment by naqushab** [comment]
@rubbesh can you show me screenshots? Are you saying you are not seeing the download icon or you want 128kbps music? Also, just add a new issue and don't rename the old issues.
