### ISSUE TITLE
Error generated while downloading

### ISSUE THREAD

**Issue by the-geek-in-glasses** [naqushab/saavn-downloader-extension#26]
while downloading some songs error is generated that prevents the songs from being downloaded i tried to understand and fix this issue but was unable to...please fix it,regards. 

![Capture](https://user-images.githubusercontent.com/50513050/66553941-abec6300-eb69-11e9-9ae5-3336f8d2f7d3.JPG)

**Comment by naqushab** [comment]
Duplicate of #30
