### ISSUE TITLE
not able to download

### ISSUE THREAD

**Issue by omendra9** [naqushab/saavn-downloader-extension#27]
![Screenshot 2019-10-18 at 10 49 50 AM](https://user-images.githubusercontent.com/29342614/67067748-19fddf00-f195-11e9-8c41-7a557b9e0cfe.png)
![Screenshot 2019-10-18 at 10 51 01 AM](https://user-images.githubusercontent.com/29342614/67067778-33069000-f195-11e9-8bb7-de37ef318840.png)

**Comment by naqushab** [comment]
Duplicate of #30
