### ISSUE TITLE
not able to download songs from this extension

### ISSUE THREAD

**Issue by Farzan1234** [naqushab/saavn-downloader-extension#28]
http://justiriser.blogspot.com/2018/12/download-songs-from-jiosaavncom-to-mp3.html

**Comment by justiriser** [comment]
> http://justiriser.blogspot.com/2018/12/download-songs-from-jiosaavncom-to-mp3.html

did u downloaded the zip file... proceed with the steps mentioned... it should work

**Comment by naqushab** [comment]
Duplicate of #30
