### ISSUE TITLE
Jiosavan web interface changed. download functionality not working

### ISSUE THREAD

**Issue by ADVALAKI** [naqushab/saavn-downloader-extension#30]
Today jiosavan change its web interface and now injaction of download button near song and on playlist not working.

so cant able to download song.

can you please fix it. 

let me know if you need more information

Thanks.

**Comment by ADVALAKI** [comment]
@naqushab can you please fix it with new jiosavan interface. 

it would be great. i try it myself but not succeed.

Thanks.

**Comment by rubbesh** [comment]
True

**Comment by naqushab** [comment]
Let me check and when I'll have some free time. I'll change it as soon as I
can. Thank you for reporting it.

**Comment by naqushab** [comment]
Fixed in #40 Make sure you follow instructions and you should be able to download songs now
