### ISSUE TITLE
128kbps not working please fix

### ISSUE THREAD

**Issue by rubbesh** [naqushab/saavn-downloader-extension#41]
![Screenshot_20200624-064644](https://user-images.githubusercontent.com/51996035/85485886-43ee8780-b5e7-11ea-8718-cc36bf89fcd6.png)
This is 320kbps working
![Screenshot_20200624-064758](https://user-images.githubusercontent.com/51996035/85485939-5b2d7500-b5e7-11ea-9780-2af22fdd16fc.png)

**Comment by rubbesh** [comment]
320kbps perfect working

**Comment by naqushab** [comment]
@rubbesh Please provide the link as well. Let me see what has to be done. :)

**Comment by naqushab** [comment]
Got the issue @rubbesh I'll fix the issue today and you should be able to get 128kbps audio as well. :)

**Comment by naqushab** [comment]
Issue fixed in [5e52099](https://github.com/naqushab/saavn-downloader-extension/commit/5e520991324e9e3183f63dffd04ab2ce1cb7f270)
128kbps downloads should now work. Shoutout to @HritwikSinghal for pointing it out earlier in a github issue.
