### ISSUE TITLE
♥️

### ISSUE THREAD

**Issue by rubbesh** [naqushab/saavn-downloader-extension#42]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by naqushab** [comment]
Hi @rubbesh ,

I looked at the GaanaAPI link that you've provided. From what I have seen the download link from the JSON was not working.
I have added a repo for Gaana Download extension but for now i am not working on it till the download url gets fixed in GaanaAPI

**Comment by rubbesh** [comment]
😍
