### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by s9ider** [naqushab/saavn-downloader-extension#45]
Could not load tha manifest" in yendex browser in Android

**Comment by rubbesh** [comment]
Bro try it, select it in file manager.👍

**Comment by rubbesh** [comment]
![Screenshot_20200709-121234](https://user-images.githubusercontent.com/51996035/87005979-85815400-c1dd-11ea-866d-87b3877e4290.png)

**Comment by naqushab** [comment]
I don't think this is designed for it. It is used only for chrome.
