### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response [BUG]

### ISSUE THREAD

**Issue by ahsanurc** [naqushab/saavn-downloader-extension#47]
**Describe the bug**
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://jiosaavn-api.herokuapp.com/result/?query=https%3A%2F%2Fwww.jiosaavn.com%2Fsong%2Ftere-naal%2FKD8zfAZpZFo with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Screenshots**
![image](https://user-images.githubusercontent.com/69759806/90336975-4a78fa00-dfad-11ea-84bb-f9b1e5a7025c.png)

**Comment by naqushab** [comment]
Should be tackled via https://github.com/naqushab/saavn-downloader-extension/pull/50

**Comment by cachecleanerjeet** [comment]
@naqushab No that was the issue with the api, that time there are no Access-Control-Allow-Origin present on the api response (maybe bcs you not update the api) so chrome blocked that.

@ahsanurc now that is fixed, closing the issue.
