### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ibgchicago** [naqushab/saavn-downloader-extension#48]
**Describe the bug**
Downlaod is not working

**To Reproduce**
1. Go to URL 'jiosaavn.com'
2. Click on 'downlaod sign'
3. See error
![Capture](https://user-images.githubusercontent.com/70726834/92183673-b87a4980-ee14-11ea-996e-d5598edebd72.JPG)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by naqushab** [comment]
Works fine.. Please specify a particular song if that is the case and be descriptive in bug description and title, it makes me and other devs easily understand the flow.

**Comment by ibgchicago** [comment]
for all the song's network errors. I am from the USA. Here is another
example

https://www.jiosaavn.com/album/abhilasha/aOeznBkIkdc_

[image: image.png]
[image: image.png]

**Comment by ibgchicago** [comment]
I have tried song work before . same setup and now it's not working.

https://www.jiosaavn.com/album/shree-swaminarayan-gungan/sxVNwJc0HEI_

**Comment by ahsanurc** [comment]
The pictures you have just uploaded are not working. Please reupload them
so the creators can see. Thank you
