### ISSUE TITLE
Backend api

### ISSUE THREAD

**Issue by cachecleanerjeet** [naqushab/saavn-downloader-extension#49]
If you think that your current api on heroku is slow then don't use heroku,

Use 
[https://songapi.thetuhin.com](https://songapi.thetuhin.com) 

Obviously that is based on my [Jiosaavn Api](https://github.com/cachecleanerjeet/jiosaavnapi) & that server is located on mumbai so you will get accurate result also, max latency 300ms

**Comment by naqushab** [comment]
awesome @cachecleanerjeet i will take a look at it. if you wish to add that functionality I can give you the contributor access to you :)

**Comment by cachecleanerjeet** [comment]
Sure ,

I will 😊

**Comment by naqushab** [comment]
Awesome. Given you a collaboration access to the repo. Thank you! :)
