### ISSUE TITLE
Question for add it on jiosaavnapi's readme?

### ISSUE THREAD

**Issue by cachecleanerjeet** [naqushab/saavn-downloader-extension#52]
Hello. @naqushab 

Can i add this project in <tt>using this api</tt> section of jiosaavnapi's readme ?

Section referance 

https://github.com/cachecleanerjeet/JiosaavnAPI#using-this-api

**Comment by naqushab** [comment]
@cachecleanerjeet Yes, please go ahead. No need to ask for permission.

**Comment by cachecleanerjeet** [comment]
Okay thanks ❤

**Comment by cachecleanerjeet** [comment]
Added 

https://github.com/cachecleanerjeet/JiosaavnAPI#using-this-api
