### ISSUE TITLE
i got the issue while downloding some songs 

### ISSUE THREAD

**Issue by ajstyles1234** [naqushab/saavn-downloader-extension#53]
i think song quality :-320kbps not working 192kbps worked for me only
 xhr.onload = function() {
        if (xhr.status === 200) {
            onload(xhr.response);
        } else {
            console.error(xhr.statusText + ' (' + xhr.status + ')');
        }
    };
    xhr.onerror = function() {
        console.error('Network error');

**Comment by cachecleanerjeet** [comment]
Yes that's bcs 320 kbps is not available for that song or not accessible,
