### ISSUE TITLE
[BUG] Get error 403

### ISSUE THREAD

**Issue by ibgchicago** [naqushab/saavn-downloader-extension#54]
[**Describe](url) the bug**

https://www.jiosaavn.com/album/surdas---sur-ke-shyam/SSSEQYR5WBw_

**To Reproduce**
1. Go to URL "https://www.jiosaavn.com/album/surdas---sur-ke-shyam/SSSEQYR5WBw_"
2. Click on download sign
3. See error (no download)

**Expected behavior**
Suppose to start download
![Capture](https://user-images.githubusercontent.com/70726834/95412866-8b2b2a80-08ef-11eb-8943-0a86d4f8d4be.JPG)

**Screenshots**

**Additional context**

**Comment by cachecleanerjeet** [comment]
Actually the mp3/mp4 link is not accessible (Common Issue). Basically you can't download this song with this extension. Try to use other options such as youtube or [musicder](https://musicder.net)

**Comment by ibgchicago** [comment]
> Actually the mp3/mp4 link is not accessible or 320kbps is not available (Common Issue). Try to download in other qualities , or use another options such as youtube or [musicder](https://musicder.net)

Musicder does not give entire album (5 out of 11 songs), does not give songs IDs (title/#/bit rate/artist/album name etc unless I am missing something in setting

**Comment by ibgchicago** [comment]
musicder only gives  4 songs from the album. I checked other albums too e.g
sur ke shyam.

**Comment by ibgchicago** [comment]
Can you check the following link. Why I can't download

https://musicder.net/download/?id=vf7njWlK

Trying to download  commentary, 8 file from "Meera prem divani"

**Comment by cachecleanerjeet** [comment]
Sir, musicder is a different project why do you create an issue of musicder here? @ibgchicago

**Comment by ibgchicago** [comment]
Sorry.

**Comment by naqushab** [comment]
Thanks @cachecleanerjeet for investigation. I use musicder. Nice app i must say! 😊

**Comment by cachecleanerjeet** [comment]
Thank you sir @naqushab
