### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by onlynir** [naqushab/saavn-downloader-extension#57]
Hello Bhai, 
I am not able to download songs from the website for the last ten days or more by using your awesome extension as Clicking on the download icon brings up a cross mark (photo attached).  Please take care of your beautiful creation and enable me to download more and more Bengali songs from the website as there is no good website that exists to download new Bengali songs and your extension is the only hope for me.

Thanks for your anticipation 

Link (https://www.jiosaavn.com/album/sos-kolkata/vfVqpgaev9g_) [Though I am not able to download any songs from any link over the website)

![Savaan](https://user-images.githubusercontent.com/66489034/97461918-37e34f80-1964-11eb-9d68-96e6e1953c3a.jpg)

### Extension not working

**Comment by kakkartushar1** [comment]
not working for me as well

**Comment by cachecleanerjeet** [comment]
Fixed https://github.com/naqushab/saavn-downloader-extension/commit/e5af385928f958970a6c4820d5e46918ebeccbd1

**Comment by naqushab** [comment]
Thanks @cachecleanerjeet

**Comment by cachecleanerjeet** [comment]
Welcome sir

**Comment by cachecleanerjeet** [comment]
@naqushab You join here https://telegram.dog/t_projects we will discuss there, and a pro like you will be verymuch good for us as well
