### ISSUE TITLE
Not doing anything

### ISSUE THREAD

**Issue by ashish261991** [naqushab/saavn-downloader-extension#58]
I have been using this since long and all of sudden it is not working on my machine,

I downloaded latest extension, When i click on download button , it takes forever and does nothing. it is happening all the time, i tried to download songs randomly then it worked but when i search a song and then try to download then it is not working.

**Comment by cachecleanerjeet** [comment]
Fixed with https://github.com/naqushab/saavn-downloader-extension/commit/d42bf2b8435733562f22161616580b947a3cc136
