### ISSUE TITLE
Song download error

### ISSUE THREAD

**Issue by TharinduWishwadeepa** [naqushab/saavn-downloader-extension#61]
I have tried to download **a song** from this Album https://www.jiosaavn.com/album/neththara-project-4/CBkWJoiP7-k_ This is a Sri Lankan music album.
So I got this error in Inspect Element -: 
Failed to load resource: https://corsdisabledsong.tuhinwin.workers.dev/556/416c84a53ef2cc07d5044eab4c4cecca_320.mp3 the server responded with a status of 403 ()
Hindi songs are downloading perfectly.

**Comment by cachecleanerjeet** [comment]
mp3 is not available for that song

**Comment by cachecleanerjeet** [comment]
Fixed with https://github.com/naqushab/saavn-downloader-extension/commit/d42bf2b8435733562f22161616580b947a3cc136
