### ISSUE TITLE
Don't download already downloaded songs (can be overridden) 

### ISSUE THREAD

**Issue by jitendra1607** [naqushab/saavn-downloader-extension#63]
Problem-
Suppose I downloaded some songs a day. Then after few days I again gets some time to download songs. The problem is that I forgot which songs I have already downloaded. So I may be downloading some of them again.

Solution-
We can save song ID in localstorage/index db which we are fetching from API. Then every new download attempt should be checked in this database, if ID matches then alert user to cancel or force download.

We can also save user preference for CANCEL or FORCE DOWNLOAD or ASK EVERYTIME for default behaviour.

This way we can build our collection without duplicates.

**Comment by cachecleanerjeet** [comment]
Will, Impliment it soon

**Comment by ghost** [comment]
Thanks, any idea about this extension.
https://github.com/naqushab/gaana-downloader-extension
