### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by ravi0239** [naqushab/saavn-downloader-extension#70]
Songs Not Downloaded, I will try to downloading song (SORRY,THAT'S AN ERROR) Showing...

**Comment by ghost** [comment]
Related issue 

#69

**Comment by tuhinpal** [comment]
You tried in mobile? Look, this extension's download feature only works with pc. So, share more details for better inspection

**Comment by tuhinpal** [comment]
Closing this issue, feel free to reopen it if the issue is not resolved.
