### ISSUE TITLE
FFMPEG caused high CPU usage

### ISSUE THREAD

**Issue by oviirup** [naqushab/saavn-downloader-extension#71]
**Describe the bug**
You are using FFMPEG to convert the mp4 file to mp4 but it usage CPU to good amount.
Che Edge task manager shows high `GPU Process`

**Screenshots**
![Screenshot 2021-05-21 005619](https://user-images.githubusercontent.com/49820575/119037644-18932a80-b967-11eb-8241-b30cdfb2a409.png)

**Comment by tuhinpal** [comment]
I don't think this is a huge deal. This is quite normal.
