### ISSUE TITLE
Website crashed while downloading multiple file at once

### ISSUE THREAD

**Issue by oviirup** [naqushab/saavn-downloader-extension#72]
If you try to download multiple songs at once, and you click multiple download button you can recreate the problem. I think it is mainly due to some conflict within ffmpeg wasm. The conflict happens when ffmpeg is requested to convert a file while it is still working on the previous one
You may solve it by adding a waiting period... maybe

![image](https://user-images.githubusercontent.com/49820575/119038050-8b040a80-b967-11eb-82b1-6251d268f7ff.png)

**Comment by chaitrakiran2010** [comment]
Temporary solution - refresh after download (shortcut KEY - F5)

**Comment by tuhinpal** [comment]
Use it wisely. It can be a memory allocation error.
