### ISSUE TITLE
SAAVN IS CHANGE NOW IS JIOSAAVN

### ISSUE THREAD

**Issue by SWARUP24** [naqushab/saavn-downloader-extension#8]
SAAVN IS CHANGE NOW IS JIOSAAVN PLEASE FIXED THIS ISSUE

**Comment by OmkarK45** [comment]
Use this updated ext https://github.com/justiriser/JioSaavn-Downloader-Chrome-Extension/blob/master/README.md

**Comment by naqushab** [comment]
The issue is now fixed. Thanks to @justiriser
